<?php

namespace App\Http\Requests;

use App\Http\Controllers\Api\UserController;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Nette\Schema\ValidationException;

class UserStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'email' => 'required|email|unique:users',
            'name' => 'required|string|max:50',
            'password' => 'required'
        ];
    }
//    protected function failedValidation(Validator $validator)
//    {
//        parent::failedValidation($validator); // TODO: Change the autogenerated stub
//        throw new \HttpResponseException(
//            new UserController()
//        )
//    }
}
